"use client";

import { useRouter } from "next/navigation";
import { ArrowLeft, Lightbulb } from "lucide-react";
import { getEmployeeById } from "../data/mockEmployees";
import CasesTable from "../../dashboard/components/CasesTable";
import AnimatedProgressCircle from "../components/AnimatedProgressCircle";
import { motion } from "framer-motion";
import { use } from "react";

export default function EmployeeDetailsPage({ params }) {
  const router = useRouter();
  const { employeeID } = use(params);
  const employee = getEmployeeById(employeeID);

  if (!employee) {
    return (
      <div className="p-8">
        <p className="text-gray-600 text-sm">Employee not found.</p>
        <button
          onClick={() => router.push("/employee-network")}
          className="mt-4 text-blue-600 hover:underline"
        >
          ← Back to All Employees
        </button>
      </div>
    );
  }

  const circleSize = 120;
  const strokeWidth = 10;
  const radius = (circleSize - strokeWidth) / 2;
  const circumference = 2 * Math.PI * radius;

  const approvedOffset =
    circumference - circumference * employee.approvedPct;
  const fraudOffset =
    circumference - circumference * employee.fraudRejectPct;

  return (
    <div className="flex flex-col gap-6">
      {/* Top Bar */}
      <div className="flex items-center gap-3 mb-4">
        <button
          onClick={() => router.push("/employee-network")}
          className="flex items-center gap-1 text-gray-600 hover:text-blue-600 transition"
        >
          <ArrowLeft className="w-4 h-4" />
          <span className="text-sm font-medium">Back</span>
        </button>
      </div>

      {/* Employee Header */}
      <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold text-gray-800">
            {employee.name}
          </h1>
          <p className="text-sm text-gray-500">{employee.role}</p>
        </div>
        <div className="text-sm text-gray-400 font-medium">
          {employee.categories.join(" • ")}
        </div>
      </div>

      {/* Metrics Section */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        {/* Approved Percentage */}
        <AnimatedProgressCircle
          value={employee.approvedPct}
          color="#3B82F6"
          label="Percentage Approved"
        />

        {/* Fraud Detected Percentage */}
        <AnimatedProgressCircle
          value={employee.fraudRejectPct}
          color="#EF4444"
          label="Percentage Rejected with Fraud Detected"
        />

        {/* Case Types */}
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 flex flex-col">
          <p className="text-sm font-medium text-gray-500 mb-3">
            Types of Cases Handled
          </p>
          <div className="space-y-2">
            {employee.categories.map((type, idx) => {
              const performance = 60 + idx * 10; // demo %
              return (
                <div key={type} className="flex items-center justify-between">
                  <span className="text-gray-700 font-medium text-sm">{type}</span>
                  <div className="w-1/2 bg-gray-100 rounded-full h-2 ml-4 overflow-hidden">
                    <motion.div
                      className="h-full bg-blue-500 rounded-full"
                      initial={{ width: 0 }}
                      animate={{ width: `${performance}%` }}
                      transition={{ duration: 1, ease: "easeOut" }}
                    />
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>

        {/* AI Analysis Section */}
        <div className="w-3/4 bg-white rounded-2xl shadow-md relative overflow-hidden border border-gray-100">
          {/* Header */}
          <div className="flex items-center justify-between px-6 py-3 border-b border-gray-100 bg-gradient-to-r from-blue-50 to-white">
            <div className="flex items-center gap-2">
              <div className="flex items-center justify-center w-7 h-7 rounded-full bg-blue-100 text-blue-600">
                <Lightbulb className="w-4 h-4" strokeWidth={2} />
              </div>
              <h2 className="text-sm font-semibold text-gray-800 tracking-wide">
                AI Analysis of Case Handling
              </h2>
            </div>
            <span className="text-xs text-gray-400 italic">Generated by SynsureAI</span>
          </div>

          {/* Body */}
          <div className="px-6 py-5 space-y-3">
            <p className="text-[15px] text-gray-800 leading-relaxed">
              {employee.aiAnalysis}
            </p>

            <div className="border-t border-gray-100 pt-3">
              <p className="text-[15px] leading-relaxed">
                <span className="font-semibold text-blue-700">Recommendation: </span>
                <span className="text-gray-800">{employee.aiRecommendation}</span>
              </p>
            </div>
          </div>
        </div>

      {/* Cases Table */}
      <CasesTable
        cases={employee.recentCases.map((c) => ({
          id: c.id,
          name: c.name,
          createdAt: c.createdAt,
          updatedAt: c.updatedAt,
        }))}
      />
    </div>
  );
}
